Feature: création d'un évènement
        Given je suis un utilisateur
        When je décide de créer un évènement
        Then l'évènement est bien rajouté

    Scenario Outline: la création d'un évènement avec succès
        Given je suis un utilisateur
        When je décide de créer un évènement:
            | description   | endDate   | name   | startDate   |
            | <description> | <endDate> | <name> | <startDate> |
        Then l'évènement a bien été ajouté <name>
        Examples:
            | description                                                                                                                                                                                                  | endDate                  | name                             | startDate                |
            | "Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème"                                                                                                                             | 2010-04-14T16:00:00.000Z | "  Meet-Up Green-It  "           | 2010-04-12T16:00:00.000Z |
            | "   Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème     "                                                                                                                     | 2199-04-14T16:00:00.000Z | evenement futur                  | 2199-04-12T16:00:00.000Z |
            | "Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            " | 2199-04-14T16:00:00.000Z | " evenement current"             | 2000-04-12T16:00:00.000Z |
            | "Le lorem ipsum (également appelé faux-texte, lipsum, ou bolo bolo1) est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en page, le texte défiee"   | 2010-04-14T16:00:00.000Z | a1234567890123456789012345678901 | 2010-04-12T16:00:00.000Z |

    Scenario Outline: la création d'un évènement avec erreur
        Given je suis un utilisateur
        When je décide de créer un évènement:
            | description   | endDate   | name   | startDate   |
            | <description> | <endDate> | <name> | <startDate> |
        Then l'évènement n'a pas été ajouté pour les raisons <erreurs>

        Examples:
            | description                                                                                                                                                                                               | endDate                  | name                              | startDate                | erreurs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            |                                                                                                                                                                                                           |                          |                                   |                          | {"errors": [{"name": {"isNotEmpty": "Le nom ne peut pas être vide", "IsNotBlankConstraint": "\"name\" doesn't contain only spaces"}}, {"description": {"isNotEmpty": "La description ne peut pas être vide","IsNotBlankConstraint": "\"description\" doesn't contain only spaces"}}, {"startDate": {"isBefore": "\"startDate\" must be before \"endDate\"", "isDate": "startDate must be a Date instance", "maxDate": "maximal allowed date for startDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for startDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}, {"endDate": {"isDate": "endDate must be a Date instance","maxDate": "maximal allowed date for endDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for endDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}]} |
            | "                                        "                                                                                                                                                                |                          |                                   |                          | {"errors": [{"name": {"isNotEmpty": "Le nom ne peut pas être vide", "IsNotBlankConstraint": "\"name\" doesn't contain only spaces"}}, {"description": {"IsNotBlankConstraint": "\"description\" doesn't contain only spaces","isNotEmpty": "La description ne peut pas être vide"}}, {"startDate": {"isBefore": "\"startDate\" must be before \"endDate\"", "isDate": "startDate must be a Date instance", "maxDate": "maximal allowed date for startDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for startDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}, {"endDate": {"isDate": "endDate must be a Date instance","maxDate": "maximal allowed date for endDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for endDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}]} |
            |                                                                                                                                                                                                           | 2010-04-18T16:00:00.000Z | "   "                             | 2010-04-12T16:00:00.000Z | {"errors": [{"name": {"IsNotBlankConstraint": "\"name\" doesn't contain only spaces", "isNotEmpty": "Le nom ne peut pas être vide"}}, {"description": {"isNotEmpty": "La description ne peut pas être vide","IsNotBlankConstraint": "\"description\" doesn't contain only spaces"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2010-04-14T16:00:00.000Z |                                   | 2010-04-12T16:00:00.000Z | {"errors": [{"name": {"isNotEmpty": "Le nom ne peut pas être vide", "IsNotBlankConstraint": "\"name\" doesn't contain only spaces"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2010-04-12T16:00:00.000Z | pas vide                          | 2010-04-12T16:00:00.000Z | {"errors": [{"startDate": {"isBefore": "\"startDate\" must be before \"endDate\""}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | Le lorem ipsum (également appelé faux-texte, lipsum, ou bolo bolo1) est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en page, le texte défieee | 2010-04-14T16:00:00.000Z | pas vide                          | 2010-04-12T16:00:00.000Z | {"errors": [{"description": {"maxLength": "La description ne doit pas dépasser 200 caractères"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2010-04-14T16:00:00.000Z | 012345678901234567890123456789012 | 2010-04-12T16:00:00.000Z | {"errors": [{"name": {"maxLength": "Le nom est trop long"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2010-04-14T16:00:00.000Z | 012345678901234567890123456789012 | 2010-04-12T16:00:00.000Z | {"errors": [{"name": {"maxLength": "Le nom est trop long"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2010-01-01:00:01.000Z    | name                              | 1899-12-31T10:59:00.000Z | {"errors": [{"startDate":{"isBefore": "\"startDate\" must be before \"endDate\"","minDate": "minimal allowed date for startDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}},{"endDate": {"isDate": "endDate must be a Date instance","maxDate": "maximal allowed date for endDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)", "minDate": "minimal allowed date for endDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2201-01-01:00:01.000Z    | name                              | 2020-02-31T10:59:00.000Z | {"errors": [{"startDate": {"isBefore": "\"startDate\" must be before \"endDate\"", "isDate": "startDate must be a Date instance", "maxDate": "maximal allowed date for startDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for startDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}},{"endDate": {"isDate": "endDate must be a Date instance","maxDate": "maximal allowed date for endDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for endDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}]}                                                                                                                                                                                                                                                                           |
            | Quels sont les outils que nous pouvons utiliser permettant avoir un ecosystème                                                                                                                            | 2022-02-31T10:59:00.000Z | name                              | 2010-04-12T16:00:00.000Z | {"errors": [{"startDate": {"isBefore": "\"startDate\" must be before \"endDate\""}},{"endDate": {"isDate": "endDate must be a Date instance","maxDate": "maximal allowed date for endDate is Wed Jan 01 2200 00:00:00 GMT+0100 (heure normale d’Europe centrale)","minDate": "minimal allowed date for endDate is Mon Jan 01 1900 00:00:00 GMT+0009 (heure normale d’Europe centrale)"}}]}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
